simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),

]

simplesocial/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/", views.UserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>/", views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>/", views.DeletePost.as_view(), name="delete"),
    path("by/<username>/<int:pk>/comment/", views.add_comment_to_post, name="add_comment_to_post"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplesocial/templates/base.html
<!doctype html>
{% load static %}
<html>
	<head>
		<meta charset="utf-8">
		<title>GymHub</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
		<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Lilita+One &family=Poppins & display=swap" rel="stylesheet">
		<style> @import url('https://fonts.googleapis.com/css2?family=Lilita+One&family=Poppins&display=swap'); </style>
		<link rel="stylesheet" href="{% static 'css/master.css' %}">
	</head>
	<body>
		<div class="background-overlay"></div>
		<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
		<div class="container-fluid">
		<a class="navbar-brand" href="{% url 'home' %}">GymHub</a>
		<ul class="nav navbar-nav navbar-right">
			{% if user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'posts:all' %}">Feed</a>
			</li>
			<li class="nav-item">
			<a class="nav-link posts" href="{% url 'posts:create' %}"> Create Post</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="{% url 'groups:all' %}">Topics</a>
			</li>
			<li class="nav-item">
			<a class="nav-link topic" href="{% url 'groups:create'%}">Create Topic</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
			</li>
			{% else %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'posts:all' %}">Feed</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="{% url 'groups:all' %}">Topics</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in" >Login</span> </a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a>
			</li>
			{% endif %}
		</ul>
		</div>
		</nav>
		
			{% block content%}
			<div class="mycontent"></div>
			{% endblock %}
		</div>
	</body>
</html>

simplesocial/templates/index.html
{% extends 'base.html' %}
{% load static %} 

{% block content %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock %}
{% if request.user.is_authenticated %}
<div class="container">
    <h1>Welcome Back to GymHub, {{ user.username }}</h1>
    <p>Keep up the great work and never give up on your fitness goals. Remember, every day is a new opportunity to push yourself and become stronger. As we like to say at GymHub, "Be strong, be healthy, be you."</p>
    <a href="{% url 'posts:all' %}" class="cta-btn">My Feed</a>
</div>
{% else %}
<div class="container">
    <h1>Welcome to GymHub</h1>
    <p>Join our vibrant community of fitness enthusiasts and achieve your goals with support from like-minded people. Share your progress, ask for advice, and get inspired on your fitness journey. </p>
    <a href="{% url 'accounts:signup' %}" class="cta-btn">Join Now</a>
</div>

{% endif %}
{% endblock %}
		
	

simplesocial/templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1>You are now logged in!</h1>

{% endblock %}

simplesocial/templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks for visiting, come back soon! </h1>
{% endblock %}