simplesocial/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/", views.UserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>/", views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>/", views.DeletePost.as_view(), name="delete"),
    path("by/<username>/<int:pk>/comment/", views.add_comment_to_post, name="add_comment_to_post"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplesocial/posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.validators import MaxLengthValidator

# pip install misaka
import misaka

from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts",
                             on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(
        Group, related_name="posts", null=True, blank=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    text = models.TextField(validators=[MaxLengthValidator(2200)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.post.id)])

    class Meta:
        ordering = ['-created_at']

simplesocial/posts/forms.py
from django import forms
from posts.models import Post, Comment


class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('text',)

      

simplesocial/posts/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic
from posts.forms import CommentForm
from django.contrib.auth.decorators import login_required

# pip install django-braces
from braces.views import SelectRelatedMixin

from . import forms
from . import models
from groups.models import Group, GroupMember

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form']= CommentForm()
        context['get_other_groups']=Group.objects.all()
        if self.request.user.is_authenticated:
            context['get_user_groups'] = Group.objects.filter(memberships__user=self.request.user)
        return context
 


class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        context['comment_form']= CommentForm()
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    comment_form = CommentForm()
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form']= CommentForm()
        return context
   

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # form_class = forms.PostForm
    fields = ('image','message','group')
    model = models.Post

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs.update({"user": self.request.user})
    #     return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)
    

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("groups:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)
    
@login_required
def add_comment_to_post(request, username, pk):
    post = get_object_or_404(models.Post, user__username=username, pk=pk)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
    return redirect('posts:single', username=post.user.username, pk=post.pk)
    
    

simplesocial/posts/templates/posts/_post.html
{% load static %} 
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/posts.css' %}">
{% endblock %}
<div class="post media">
	<a href="{% url 'posts:single' username=post.user.username pk=post.pk %}" title=""><h3>{{post.message_html|safe}}</h3></a>
	<div class="media-body">
		{% if post.image %}
		<div class="post_img"><img src="{{ post.image.url }}" width=100% alt="Post Image"></div>
		{% endif %}
		by user:
		<strong><a href="{% url 'posts:for_user' username=post.user.username %}" title="">{{post.user.username}}</a></strong>
	<div class="media-footer">
		<button id="comment-toggle-{{ post.pk }}" class="btn btn-success">Add Comment</button>
		
		{% if user.is_authenticated and post.user == user and not hide_delete %}
		<a href="{% url 'posts:delete' pk=post.pk%}" title="delete" class="btn btn-simple"><div class="text-danger icon-label delete-btn">Delete Post</div></a>
		{% endif %}
		<div id="comment-form-{{ post.pk }}" style="display:none;" class="post-form">
			<form method="POST" action="{% url 'posts:add_comment_to_post' username=post.user.username pk=post.pk %}">
			  {% csrf_token %}
			  {{ comment_form.as_p }}
			  <button type="submit">Submit</button>
			</form>
		  </div>
	</div>
	<div class="comments">
		{% for comment in post.comments.all %}
  <br>

          <div class="date postdate">
            <small>{{ comment.create_date }}</small>
          </div>
      <h2>{{ comment.text|safe|linebreaks }}</h2>
      <p>Posted by: <strong>{{ comment.author }}</strong></p>
  {% empty %}
      <p>No comments posted.</p>
  {% endfor %}
	</div>
</div>
</div>

simplesocial/posts/templates/posts/post_base.html
{% extends 'base.html' %}
{% block content %}
<style>
	.post_content {
		max-width:98vw;
	}
</style>
	<div class="post_content">
		<div class="row">
			{% block prepost %}{% endblock %}
			{% block post_content %}{% endblock %}
			{% block post_post %}{% endblock %}
		</div>
	</div>
{% endblock %}

simplesocial/posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
<div class="container">
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include 'posts/_post.html' with post=object hide_delete=True %}
</div>

<form method="post">
	{% csrf_token %}
	<input type='submit' value='Confirm Delete' class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" title="" class="btn btn-secondary me-2">Cancel</a>
</form>
</div>
{% endblock %}

simplesocial/posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
{% load static %} 
<div class="container">
<div class="col-md-8">
	{% include 'posts/_post.html' %}
	<script src="{% static 'js/list.js' %}"></script>
</div>
</div>
{% endblock %}

simplesocial/posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap4 %}
{% block post_content %}
{% load static %} 
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
{% endblock %}
<div class="container create">
<h4>Create a new Post</h4>
<form id="postForm" action="{% url 'posts:create' %}" method='post' enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value='Post' class='btn btn-primary btn-large'>
</form>
</div>
{% endblock %}

simplesocial/posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}
{% block prepost %}
{% load static %} 
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
{% endblock %}

<div class="col-md-3">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<a href="{% url 'posts:for_user' username=user.username%}" title=""><h1 class="title">My Profile</h1></a>
		</div>
	</div>
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Topics</h5>
			{% if not get_user_groups %}
			<div>No Topics Joined</div>
			{% endif %}
			<ul class="list-unstyled">
				{% for member_group in get_user_groups %}
				<li><a href="{% url 'groups:single' slug=member_group.slug %}">{{member_group.name}}</a></li>
				{% endfor%}
			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All Topics</h5>
			<ul class="list-unstyled">
				{% for other_group in get_other_groups %}
				<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{other_group.name}}</a></li>
				{% endfor%}
			</ul>
		</div>
	</div>
</div>
{% endblock %}


{% block post_content %}

<div class="col-md-8">
	{% for post in post_list %}
	{% include 'posts/_post.html' %}
	{% endfor %}
</div>
<script src="{% static 'js/list.js' %}"></script>
{% endblock %}

simplesocial/posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}
{% block prepost %}
<div class="container">
<div class="'col-md-4">
	<h1>@{{post_user.username}}</h1>
</div>
{% endblock %}

{% block post_content %}
{% load static %} 
<div class="col-md-8">
	{% for post in post_list %}
	{% include 'posts/_post.html' %}
	{% endfor %}
</div>
</div>
<script src="{% static 'js/list.js' %}"></script>
{% endblock %}